### ISSUE TITLE
SocialWorker Account Privileges

### ISSUE THREAD

**Issue by annarog** [adriannadiaz/SocialWorker#31]
As an admin social worker, I want to limit the privilege access of other workers or interns.

- [x] Make two classes of social workers {Administrative users,Regular users}
- Admins can add/delete user accounts, permanently delete records (Participants, Casefiles, Resources, ...) from the database. Admins can assign and reassign Users to Participants.
- Users can add records to the database, if they delete records, they are only **marked** as deleted, users can only access certain Participant profiles, those that they are assigned to. 

- [x] Add link to social worker in the Participant model
- [x] Change the Participant service so it only returns participants that are associated with the querying social worker

- [x] Testing

Priority: [Med]
USP: [3]

**Comment by adriannadiaz** [comment]
I removed Francis from this ticket because even though he was assigned, he did not collaborate in it.
